queue_rules:
  - name: default
    commit_message_template: |-
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: put PRs in queue (squash)
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - -label~=(do-not-merge)
      - status-success=build
    actions:
      queue:
        name: default
        merge_method: squash

  - name: Label core contributions
    conditions:
      - author~=^(pgollucci)$
      - label!=contribution/core
    actions:
      label:
        add:
          - contribution/core

  - name: Label auto-merge for core
    conditions:
      - label=contribution/core
      - label!=auto-merge
    actions:
      label:
        add:
          - auto-merge

merge_queue:
  max_parallel_checks: 1

